### ISSUE TITLE
Пошаманить с  IParameterReader

### ISSUE THREAD

**Issue by AidarValshin** [VerstovDI/FileSystem#10]
создал класс ReaderParameters в  Functions.ParameterReaders  в нем есть методы, вам надобно будет:
1. Добавить свои методы туда
2. Удалить все свои кастомные Reder ы
После удаления всех кастомных
3. Добавить эти же методы из (1)  как абстрактные в IParameterReader
4. Удалить метод   IParameterReader ParameterReader () из интерфейса

**Comment by VerstovDI** [comment]
done
